0.1.17

diff --git a/bin/sparky-codecs b/bin/sparky-codecs
--- a/bin/sparky-codecs
+++ b/bin/sparky-codecs
@@ -7,7 +7,7 @@
 # Copyright 2014-2018 Paweł "pavroo" Pijanowski <pavroo@onet.eu>
 # Licensed under the GPLv2 license
 # see /usr/share/common-licenses/GPL-2 
-# Last update 2018/03/20
+# Last update 2018/03/29
 
 # get default's locale file
 DEFLOCDIR="/usr/share/sparky/sparky-codecs"
@@ -47,10 +47,11 @@ TEXT="--text="
 OKEXIT=" --button=Ok:0 --button=Exit:1"
 MSGBOX="--button=Ok:0"
 TITLETEXT="Sparky Codecs"
-if [ -f /usr/bin/sparky-terminal ]; then
-	SPARKYXTERM="sparky-terminal"
+if [ -f /usr/bin/sparky-xterm ];then
+	SPARKYXTERM="/usr/bin/sparky-xterm"
 else
-	SPARKYXTERM="x-terminal-emulator"
+	echo "sparky-xterm is missing... Exiting..."
+	exit 1
 fi
 
 ARCH64="`uname -m | grep x86_64`"
@@ -76,23 +77,23 @@ else
 
 	if [ "$ARCH64" != "" ]; then
 
-		$SPARKYXTERM -e "apt-get update"
-		$SPARKYXTERM -e "apt-get install gstreamer1.0-fluendo-mp3 gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly x264 x265 libdvd-pkg libdvdread4 ffmpeg flashplayer-mozilla icedtea-plugin lame browser-plugin-vlc w64codecs"
-		$SPARKYXTERM -e "apt-get install -f"
+		$SPARKYXTERM "apt-get update"
+		$SPARKYXTERM "apt-get install gstreamer1.0-fluendo-mp3 gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly x264 x265 libdvd-pkg libdvdread4 ffmpeg flashplayer-mozilla icedtea-plugin lame browser-plugin-vlc w64codecs"
+		$SPARKYXTERM "apt-get install -f"
 		$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"\n$LOCAL7"
 
 	elif [ "$ARCH32" != "" ]; then
 
-		$SPARKYXTERM -e "apt-get update"
-		$SPARKYXTERM -e "apt-get install gstreamer1.0-fluendo-mp3 gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly x264 x265 libdvd-pkg libdvdread4 ffmpeg flashplayer-mozilla icedtea-plugin lame browser-plugin-vlc w632codecs"
-		$SPARKYXTERM -e "apt-get install -f"
+		$SPARKYXTERM "apt-get update"
+		$SPARKYXTERM "apt-get install gstreamer1.0-fluendo-mp3 gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly x264 x265 libdvd-pkg libdvdread4 ffmpeg flashplayer-mozilla icedtea-plugin lame browser-plugin-vlc w632codecs"
+		$SPARKYXTERM "apt-get install -f"
 		$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"\n$LOCAL7"
 	
 
 	elif [ "$ARCHARM" != "" ]; then
-		$SPARKYXTERM -e "apt-get update"
-		$SPARKYXTERM -e "apt-get install gstreamer1.0-fluendo-mp3 gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly x264 x265 libdvd-pkg libdvdread4 ffmpeg icedtea-plugin lame browser-plugin-vlc"
-		$SPARKYXTERM -e "apt-get install -f"
+		$SPARKYXTERM "apt-get update"
+		$SPARKYXTERM "apt-get install gstreamer1.0-fluendo-mp3 gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly x264 x265 libdvd-pkg libdvdread4 ffmpeg icedtea-plugin lame browser-plugin-vlc"
+		$SPARKYXTERM "apt-get install -f"
 		$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"\n$LOCAL7"
 
 	fi
